//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeafileOutlookAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeafileOutlookAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string AboutBtnText {
            get {
                return ResourceManager.GetString("AboutBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap aboutpng {
            get {
                object obj = ResourceManager.GetObject("aboutpng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 访问URL.
        /// </summary>
        internal static string AccessUrl {
            get {
                return ResourceManager.GetString("AccessUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置文件解析错误.
        /// </summary>
        internal static string ConfigParseError {
            get {
                return ResourceManager.GetString("ConfigParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码为空.
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传文件不能为空.
        /// </summary>
        internal static string EmptyUploadFile {
            get {
                return ResourceManager.GetString("EmptyUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到&quot;{0}&quot;。.
        /// </summary>
        internal static string ExceptionFileNotFound {
            get {
                return ResourceManager.GetString("ExceptionFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不支持将多个包附加至一封Outlook电子邮件。.
        /// </summary>
        internal static string ExceptionNoMoreThanOnePackageAsAttachment {
            get {
                return ResourceManager.GetString("ExceptionNoMoreThanOnePackageAsAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名或密码错误.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attached package has been sent with Seafile. To edit .velodoc files or send large files from Outlook, please download Memba Velodoc Outlook Add-In from {0}..
        /// </summary>
        internal static string MessageBodyAdvertisement {
            get {
                return ResourceManager.GetString("MessageBodyAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----Original Message-----.
        /// </summary>
        internal static string MessageBodyForwardReplyTextRegex {
            get {
                return ResourceManager.GetString("MessageBodyForwardReplyTextRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attached package contains links to download the following files:.
        /// </summary>
        internal static string MessageBodyLinksHeader {
            get {
                return ResourceManager.GetString("MessageBodyLinksHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string MessageBoxErrorTitle {
            get {
                return ResourceManager.GetString("MessageBoxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string MessageBoxInfoTitle {
            get {
                return ResourceManager.GetString("MessageBoxInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告.
        /// </summary>
        internal static string MessageBoxWarningTitle {
            get {
                return ResourceManager.GetString("MessageBoxWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享链接：.
        /// </summary>
        internal static string OutlookShare {
            get {
                return ResourceManager.GetString("OutlookShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码输入不一致.
        /// </summary>
        internal static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码（至少8个字符）.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件不存在或文件读取错误！.
        /// </summary>
        internal static string ReadFileError {
            get {
                return ResourceManager.GetString("ReadFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap seafile_logo {
            get {
                object obj = ResourceManager.GetObject("seafile-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请先设置账号.
        /// </summary>
        internal static string SetAccount {
            get {
                return ResourceManager.GetString("SetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        internal static string SettingBtnText {
            get {
                return ResourceManager.GetString("SettingBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap settingpng {
            get {
                object obj = ResourceManager.GetObject("settingpng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加.
        /// </summary>
        internal static string ShareBtnText {
            get {
                return ResourceManager.GetString("ShareBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享.
        /// </summary>
        internal static string ShareFile {
            get {
                return ResourceManager.GetString("ShareFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分享链接数据解析错误.
        /// </summary>
        internal static string SharelinkParseError {
            get {
                return ResourceManager.GetString("SharelinkParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  密码.
        /// </summary>
        internal static string SharePassword {
            get {
                return ResourceManager.GetString("SharePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sharepng {
            get {
                object obj = ResourceManager.GetObject("sharepng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上 传.
        /// </summary>
        internal static string UploadBtn {
            get {
                return ResourceManager.GetString("UploadBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上传.
        /// </summary>
        internal static string UploadBtnText {
            get {
                return ResourceManager.GetString("UploadBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uploadpng {
            get {
                object obj = ResourceManager.GetObject("uploadpng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
